CREATE TABLE letter_of_credit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lc_reference VARCHAR(30) NOT NULL UNIQUE,
    applicant_name VARCHAR(255) NOT NULL,
    beneficiary_name VARCHAR(255) NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(30) NOT NULL
        CHECK (status IN (
            'ISSUED',
            'UNDER_EXAMINATION',
            'COMPLIANT',
            'DISCREPANT',
            'SETTLED',
            'REFUSED',
            'EXPIRED'
        )),
    expiry_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE letter_of_credit_required_documents (
    letter_of_credit_id BIGINT NOT NULL,

    required_documents VARCHAR(30) NOT NULL
        CHECK (required_documents IN (
            'COMMERCIAL_INVOICE',
            'BILL_OF_LADING',
            'PACKING_LIST',
            'INSURANCE_CERTIFICATE',
            'CERTIFICATE_OF_ORIGIN'
        )),

    CONSTRAINT fk_lc_required_documents
        FOREIGN KEY (letter_of_credit_id)
        REFERENCES letter_of_credit(id)
);